name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  workspace:
    name: Workspace CI
    runs-on: ubuntu-latest

    permissions:
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Lint
        run: deno lint

      - name: Lint
        run: deno fmt

  local:
    name: Local Agent CI
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build local agent
        run: bash compile-all.sh
        working-directory: lightagent-local
