name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  workspace:
    name: Workspace CI
    runs-on: ubuntu-latest

    permissions:
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install deps
        run: deno install

      - name: Lint
        run: deno lint

      - name: Format
        run: deno fmt --check

      - name: Test core
        run: deno task test
        working-directory: lightagent-core

  local:
    name: Local Agent CI
    runs-on: ubuntu-latest
    needs: [workspace]

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install deps
        run: deno install

      - name: Build local agent
        run: bash compile-all.sh
        working-directory: lightagent-local

      - name: Run local tests
        run: deno test -A
        working-directory: lightagent-local

  durable-object:
    name: DO Agent CI
    runs-on: ubuntu-latest
    needs: [workspace]

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install deps
        run: deno install

      - name: Build DO agent
        run: deno task bundle
        working-directory: lightagent-do
